###############################################################################
# main.tf — Security Group, Key Pair, EC2 instance, hosts.ini generation
###############################################################################

# ── SSH Key Pair — generated by Terraform, no manual steps needed ─────────────

# Generate RSA 4096 private key locally
resource "tls_private_key" "kind_node" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# Upload the public key to AWS as a named key pair
resource "aws_key_pair" "kind_node" {
  key_name   = var.key_pair_name
  public_key = tls_private_key.kind_node.public_key_openssh

  tags = merge(local.common_tags, {
    Name = var.key_pair_name
  })
}

# Save the private key as a .pem file on your local machine
resource "local_sensitive_file" "pem" {
  content         = tls_private_key.kind_node.private_key_pem
  filename        = local.pem_path
  file_permission = "0600"   # SSH refuses keys with loose permissions
}

# ── Security Group ────────────────────────────────────────────────────────────

resource "aws_security_group" "kind_node" {
  name        = local.sg_name
  description = "Security group for ${local.name_prefix} kind cluster EC2"
  vpc_id      = data.aws_vpc.default.id

  tags = merge(local.common_tags, {
    Name = local.sg_name
  })
}

# SSH — restricted to your IP only
resource "aws_vpc_security_group_ingress_rule" "ssh" {
  security_group_id = aws_security_group.kind_node.id
  description       = "SSH from my IP"
  from_port         = 22
  to_port           = 22
  ip_protocol       = "tcp"
  cidr_ipv4         = var.my_ip

  tags = merge(local.common_tags, {
    Name = "${local.sg_name}-ssh"
  })
}

# App port — kind maps NodePort 30080 → hostPort var.app_port (8888)
resource "aws_vpc_security_group_ingress_rule" "app" {
  security_group_id = aws_security_group.kind_node.id
  description       = "SkillPulse frontend via kind NodePort"
  from_port         = var.app_port
  to_port           = var.app_port
  ip_protocol       = "tcp"
  cidr_ipv4         = var.my_ip

  tags = merge(local.common_tags, {
    Name = "${local.sg_name}-app"
  })
}

# All outbound — needed for apt updates, DockerHub pulls, GitHub API
resource "aws_vpc_security_group_egress_rule" "all_outbound" {
  security_group_id = aws_security_group.kind_node.id
  description       = "All outbound traffic"
  ip_protocol       = "-1"
  cidr_ipv4         = "0.0.0.0/0"

  tags = merge(local.common_tags, {
    Name = "${local.sg_name}-egress"
  })
}

# ── EC2 Instance ──────────────────────────────────────────────────────────────

resource "aws_instance" "kind_node" {
  ami                         = data.aws_ami.ubuntu_24.id
  instance_type               = var.instance_type
  key_name                    = aws_key_pair.kind_node.key_name
  vpc_security_group_ids      = [aws_security_group.kind_node.id]
  associate_public_ip_address = true

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.volume_size_gb
    delete_on_termination = true
    encrypted             = true
  }

  tags = merge(local.common_tags, {
    Name = local.instance_name
  })
}

# ── Ansible hosts.ini — auto-generated after terraform apply ──────────────────
# Written to ansible/hosts.ini relative to where you run terraform
# Ready to use directly with: ansible-playbook -i ../ansible/hosts.ini playbook.yml

resource "local_file" "hosts_ini" {
  filename = "${path.module}/../ansible/hosts.ini"
  content  = <<-INI
    # Auto-generated by Terraform — do not edit manually
    # Regenerate with: terraform apply

    [kind_node]
    ${local.instance_name} ansible_host=${aws_instance.kind_node.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${local.pem_path}

    [kind_node:vars]
    ansible_python_interpreter=/usr/bin/python3
    ansible_ssh_common_args='-o StrictHostKeyChecking=no'
  INI

  # Wait for the instance to exist before writing
  depends_on = [aws_instance.kind_node]
}

