name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'k8s/**'
      - 'docs/**'
      - '**/*.md'
jobs:

  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml
    secrets: inherit

  docker-lint:
    uses: ./.github/workflows/docker-lint.yml

  docker-build-push:
    needs: [code-quality, secrets-scan, dependency-scan, docker-lint]
    uses: ./.github/workflows/docker_build_push.yml
    secrets: inherit

  docker-image-scan:
    needs: [docker-build-push]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
